name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch or manually from the Actions tab
  push:
    branches:
      - main
      - test
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch using git
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Restore build files
        id: cache-main-dist
        uses: actions/cache@v3
        with:
          path: ./packages/kite-chat-docs/dist
          key: ${{ runner.os }}-dist-main-${{ hashFiles('./package-lock.json') }}

      - name: List Cached Files
        if: steps.cache-main-dist.outputs.cache-hit == 'true'
        run: ls -l ./packages/kite-chat-docs/dist

      - name: Install dependencies
        if: steps.cache-main-dist.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Docs
        if: steps.cache-main-dist.outputs.cache-hit != 'true'
        run: npm run build -w @pragmasoft-ukraine/kite-chat-docs

      - name: Upload Main Artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-dist
          path: ./packages/kite-chat-docs/dist/

  build_test:
    needs: build_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch using git
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Restore main build files
        uses: actions/download-artifact@v2
        with:
          name: main-dist

      - name: Restore test build files
        id: cache-test-dist
        uses: actions/cache@v3
        with:
          path: ./packages/kite-chat-docs/dist
          key: ${{ runner.os }}-dist-main-${{ hashFiles('./package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        if: steps.cache-test-dist.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Kite Chat component
        if: steps.cache-test-dist.outputs.cache-hit != 'true'
        run: npm run build -w @pragmasoft-ukraine/kite-chat-component

      - name: Build Kite Chat
        if: steps.cache-test-dist.outputs.cache-hit != 'true'
        run: npm run build -w @pragmasoft-ukraine/kite-chat

      - name: Build Docs for Test
        if: steps.cache-test-dist.outputs.cache-hit != 'true'
        run: npm run build:test -w @pragmasoft-ukraine/kite-chat-docs

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./packages/kite-chat-docs/dist/

  deploy:
    needs: [build_main, build_test]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy Docs to GitHub Pages
        uses: actions/deploy-pages@v1